# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('parent_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_group',
            },
        ),
        migrations.CreateModel(
            name='GroupRoleRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_group_role_relation',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('group_type', models.IntegerField()),
                ('group_name', models.CharField(default='', max_length=128)),
                ('limit_name', models.CharField(max_length=32)),
                ('param', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'core_limit',
            },
        ),
        migrations.CreateModel(
            name='OPLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('method', models.CharField(max_length=256)),
                ('time', models.BigIntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('mac_address', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'core_op_log',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'core_role',
            },
        ),
        migrations.CreateModel(
            name='RoleLimitRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('limit_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_role_limit_relation',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('expire_time', models.BigIntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('mac_address', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'core_session',
            },
        ),
        migrations.CreateModel(
            name='Sys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('state', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'core_sys',
            },
        ),
        migrations.CreateModel(
            name='SysInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField()),
                ('url', models.CharField(max_length=512)),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'core_sys_interface',
            },
        ),
        migrations.CreateModel(
            name='SysLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('limit_name', models.CharField(max_length=256)),
                ('sys_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_sys_limit',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expire_time', models.BigIntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('mac_address', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'core_token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=128)),
                ('state', models.IntegerField()),
                ('is_super_user', models.IntegerField(default=0)),
                ('last_login_time', models.BigIntegerField()),
                ('create_time', models.BigIntegerField()),
                ('create_ip', models.CharField(max_length=20)),
                ('last_login_ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'core_user',
            },
        ),
        migrations.CreateModel(
            name='UserGroupRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_user_group_relation',
            },
        ),
        migrations.CreateModel(
            name='UserRoleRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_user_role_relation',
            },
        ),
        migrations.CreateModel(
            name='UserSysLimitRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('sys_limit_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_user_sys_limit_relation',
            },
        ),
    ]
