# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-11 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20180317_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('token_id', models.UUIDField(default=uuid.uuid4)),
                ('expire_time', models.BigIntegerField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'core_auth_code',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
