# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20180411_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSysRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('sys_id', models.IntegerField()),
            ],
            options={
                'db_table': 'core_role_sys_relation',
            },
        ),
    ]
